### ISSUE TITLE
love this repo? but one request

### ISSUE THREAD

**Issue by ghost** [mvhs-apps/mvhs-app#1]
Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\user\Desktop\mvhs-app\app\src\debug\google-services.json
  C:\Users\user\Desktop\mvhs-app\app\google-services.json

can you guys make it all open source?

No Google Services. They're alot of people who use  (Micro-G + SuperSU + F-Droid)
majority of don't use G-apps but alternatives. 

kind regards,
Kadwa

**Comment by pluscubed** [comment]
The app uses Google Maps and other APIs. The json file contains those keys, which you'll have to register yourself on Google's API platform.
